
'use client';

import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { LiverReport } from '@/types/report';
import toast from 'react-hot-toast';
import { marked } from 'marked';

/**
 * PDFExportButton Component
 *
 * This component provides a button to export a patient's liver report as a PDF.
 * It dynamically generates an HTML structure based on the report data, template,
 * and optional prescription, then opens a new window to trigger the browser's
 * native print functionality. This approach is used to ensure robust PDF generation
 * compatible with modern CSS features and frameworks like Tailwind CSS v4 in Next.js 15.
 *
 * @param {object} props - The properties for the component.
 * @param {LiverReport} props.report - The liver report data to be included in the PDF.
 * @param {any} props.template - The report template data, including branding colors, hospital name, and logo URL.
 * @param {any} [props.prescription] - Optional prescription data to be included in the report.
 * @param {string} [props.doctorName] - Optional name of the doctor to be displayed on the prescription.
 */
export default function PDFExportButton({
    report,
    template,
    prescription,
    doctorName
}: {
    report: LiverReport;
    template: any;
    prescription?: any;
    doctorName?: string;
}) {
    // State to manage the loading status during the PDF export process.
    const [isExporting, setIsExporting] = useState(false);

    /**
     * Handles the PDF export process.
     * It constructs an HTML string for the report, opens a new window, writes the HTML to it,
     * and then triggers the browser's print dialog.
     */
    const handleExport = async () => {
        setIsExporting(true); // Set exporting state to true.
        try {
            // Because html2canvas inherently crashes when attempting to parse Tailwind v4's globally-injected root oklch/lab variables
            // from the document stylesheets (even when isolated in iframes or passed as strings), the most robust and elegant
            // solution for Next.js 15 App Router is utilizing a clean, sandboxed native print window.
            const newWindow = window.open('', '_blank'); // Open a new blank window for printing.
            if (!newWindow) {
                toast.error("Please allow popups to generate PDF"); // Inform user if popups are blocked.
                return;
            }

            // Extract branding and report details from template and report data, with fallbacks.
            const brandingColor = template?.primary_color || '#1E3A8A';
            const hospitalName = template?.hospital_name || 'Liver Analysis Clinic';
            const disclaimer = template?.disclaimer_text || 'This report is generated by an AI assistant based on inputted lab values. It is not a substitute for professional medical advice.';

            // Parse AI summary markdown to HTML.
            const aiSummaryHtml = report.ai_summary ? await marked.parse(report.ai_summary) : 'No AI summary was generated for this report.';

            // Construct the main HTML content for the report.
            const htmlString = `
                <div style="font-family: Arial, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; background-color: #ffffff;">
                    
                    <!-- Report Header Section: Displays hospital branding, report title, date, and ID. -->
                    <div style="border-bottom: 3px solid ${brandingColor}; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end;">
                        <div>
                            ${template?.logo_url ? `<img src="${template.logo_url}" alt="Logo" style="max-height: 60px; margin-bottom: 10px;" />` : ''}
                            <h1 style="color: ${brandingColor}; margin: 0; font-size: 28px;">${hospitalName}</h1>
                            <p style="margin: 5px 0 0 0; font-size: 14px; color: #666;">Liver Function Analysis Report</p>
                        </div>
                        <div style="text-align: right; font-size: 12px; color: #555;">
                            <p style="margin: 0;">Date: ${new Date(report.created_at).toLocaleDateString()}</p>
                            <p style="margin: 5px 0 0 0;">Report ID: ${report.id.substring(0, 8)}...</p>
                        </div>
                    </div>

                    <!-- Patient Information Section: Displays patient's name, age, gender, and overall risk level. -->
                    <div style="background-color: #f9fafb; padding: 15px 20px; border-radius: 8px; margin-bottom: 30px;">
                        <table style="width: 100%; border-collapse: collapse;">
                            <tr>
                                <td style="padding: 5px 0; width: 50%;"><strong>Patient Name:</strong> ${report.patient_name}</td>
                                <td style="padding: 5px 0; width: 50%;"><strong>Risk Level:</strong> <span style="color: ${report.risk_level === 'High' ? '#DC2626' : report.risk_level === 'Moderate' ? '#D97706' : '#059669'}; font-weight: bold;">${report.risk_level.toUpperCase()} (Score: ${report.risk_score})</span></td>
                            </tr>
                            <tr>
                                <td style="padding: 5px 0;"><strong>Age:</strong> ${report.age} years</td>
                                <td style="padding: 5px 0;"><strong>Gender:</strong> ${report.gender}</td>
                            </tr>
                        </table>
                    </div>

                    <!-- Laboratory Results Section: Details key liver function test results and their reference ranges. -->
                    <h3 style="color: ${brandingColor}; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">Laboratory Results</h3>
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 40px;">
                        <thead>
                            <tr style="background-color: #f3f4f6; text-align: left;">
                                <th style="padding: 12px; border: 1px solid #e5e7eb;">Test</th>
                                <th style="padding: 12px; border: 1px solid #e5e7eb;">Result</th>
                                <th style="padding: 12px; border: 1px solid #e5e7eb;">Reference Range</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">Total Bilirubin</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.total_bilirubin} mg/dL</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">0.1 - 1.2 mg/dL</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">Albumin</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.albumin} g/dL</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">3.4 - 5.4 g/dL</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">SGPT (ALT)</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.sgpt} U/L</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">7 - 56 U/L</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">SGOT (AST)</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.sgot} U/L</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">8 - 48 U/L</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">Alk Phosphate</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.alk_phosphate || 'N/A'} U/L</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">44 - 147 U/L</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">Prothrombin Time</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.protime || 'N/A'} s</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">11 - 13.5 s</td>
                            </tr>
                        </tbody>
                    </table>

                    <!-- Clinical Indicators Section: Summarizes patient's symptoms and historical factors. -->
                    <h3 style="color: ${brandingColor}; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">Clinical Indicators</h3>
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 40px;">
                        <tbody>
                            <tr>
                                <td style="padding: 10px; border-bottom: 1px solid #f3f4f6; width: 50%;"><strong>Fatigue:</strong> <span style="color: ${report.fatigue ? '#d97706' : '#059669'};">${report.fatigue ? 'Yes' : 'No'}</span></td>
                                <td style="padding: 10px; border-bottom: 1px solid #f3f4f6; width: 50%;"><strong>Spider Naevi:</strong> <span style="color: ${report.spiders ? '#d97706' : '#059669'};">${report.spiders ? 'Yes' : 'No'}</span></td>
                            </tr>
                            <tr>
                                <td style="padding: 10px; border-bottom: 1px solid #f3f4f6;"><strong>Ascites:</strong> <span style="color: ${report.ascites ? '#dc2626' : '#059669'};">${report.ascites ? 'Yes' : 'No'}</span></td>
                                <td style="padding: 10px; border-bottom: 1px solid #f3f4f6;"><strong>Varices:</strong> <span style="color: ${report.varices ? '#dc2626' : '#059669'};">${report.varices ? 'Yes' : 'No'}</span></td>
                            </tr>
                            <tr>
                                <td style="padding: 10px; border-bottom: 1px solid #f3f4f6;"><strong>Steroid Use:</strong> <span style="color: ${report.steroid ? '#d97706' : '#059669'};">${report.steroid ? 'Yes' : 'No'}</span></td>
                                <td style="padding: 10px; border-bottom: 1px solid #f3f4f6;"><strong>Antiviral Use:</strong> <span style="color: ${report.antivirals ? '#d97706' : '#059669'};">${report.antivirals ? 'Yes' : 'No'}</span></td>
                            </tr>
                            <tr>
                                <td colspan="2" style="padding: 10px; border-bottom: 1px solid #f3f4f6;"><strong>Histology Level:</strong> <span style="font-weight: bold; color: #1E3A8A;">${report.histology || 'None'}</span></td>
                            </tr>
                        </tbody>
                    </table>

                    <!-- AI Medical Synthesis Section: Displays the AI-generated summary of the report. -->
                    <h3 style="color: ${brandingColor}; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">AI Medical Synthesis</h3>
                    <div style="background-color: #f8fafc; padding: 20px; border-left: 4px solid ${brandingColor}; line-height: 1.6; font-size: 14px; margin-bottom: 50px;">
                        ${aiSummaryHtml}
                    </div>

                    ${prescription ? `
                    <!-- Doctor Prescription Section (conditionally rendered if prescription data is available). -->
                    <h3 style="color: ${brandingColor}; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">Doctor Prescription</h3>
                    <div style="background-color: #fafafa; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; margin-bottom: 50px;">
                        <div style="display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px dashed #d1d5db; padding-bottom: 15px; margin-bottom: 20px;">
                            <div>
                                <h4 style="margin: 0; font-size: 20px; color: #111827;">${doctorName || 'Hepatology Specialist'}</h4>
                                <p style="margin: 5px 0 0 0; font-size: 12px; font-weight: bold; color: #2563EB; text-transform: uppercase; letter-spacing: 1px;">Hepatology Specialist</p>
                            </div>
                            <p style="margin: 0; font-size: 24px; color: #6B7280; font-family: monospace; font-weight: bold;">Rx</p>
                        </div>
                        
                        <div style="font-size: 15px; color: #374151; line-height: 1.8; min-height: 120px; white-space: pre-wrap; font-family: 'Courier New', Courier, monospace;">${prescription.prescription_text}</div>
                        
                        ${prescription.follow_up_date ? `
                        <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #e5e7eb; font-size: 14px; display: flex; align-items: center; gap: 8px;">
                            <span style="font-weight: bold; color: #4b5563;">Follow-up Recommended:</span> 
                            <span style="color: #1E3A8A; font-weight: bold;">${new Date(prescription.follow_up_date).toLocaleDateString()}</span>
                        </div>
                        ` : ''}
                        
                        <div style="margin-top: 40px; padding-top: 15px; border-top: 2px dashed #d1d5db; text-align: right;">
                            <div style="display: inline-block; text-align: center; width: 200px;">
                                <div style="height: 20px; border-bottom: 1px solid #9ca3af; margin-bottom: 8px;"></div>
                                <p style="margin: 0; font-size: 12px; color: #6b7280; font-weight: bold;">Doctor Signature</p>
                            </div>
                        </div>
                    </div>
                    ` : ''}

                    <!-- Footer -->
                    <div style="margin-top: auto; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; font-size: 10px; color: #888;">
                        <p>${disclaimer}</p>
                    </div>
                </div>
            `;

            // Write the complete HTML string to the new window's document.
            // This includes the HTML structure, head with title and print styles, and the body with the report content.
            newWindow.document.write(`
                <html>
                    <head>
                        <title>Liver_Report_${report.patient_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}</title>
                        <style>
                            @media print {
                                @page { margin: 10mm; }
                                body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                            }
                        </style>
                    </head>
                    <body onload="setTimeout(() => { window.print(); window.close(); }, 250);">
                        ${htmlString}
                    </body>
                </html>
            `);
            newWindow.document.close(); // Close the document to ensure all content is rendered.

            toast.success("PDF Exported Successfully"); // Show success notification.

        } catch (error) {
            console.error(error); // Log any errors during the export process.
            toast.error("Failed to generate PDF"); // Show error notification to the user.
        } finally {
            setIsExporting(false); // Reset exporting state.
        }
    };

    return (
        <div className="flex items-center gap-3 no-print">
            <button
                onClick={handleExport}
                disabled={isExporting} // Disable button while exporting.
                className="flex items-center gap-2 px-5 py-2.5 bg-[#1E3A8A] hover:bg-[#152b66] text-white rounded-lg font-bold text-sm transition-colors shadow-sm disabled:opacity-70 disabled:cursor-not-allowed"
            >
                {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                {isExporting ? 'Generating...' : 'Export PDF'}
            </button>
        </div>
    );
}
