'use client';

import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { LiverReport } from '@/types/report';
import toast from 'react-hot-toast';
import { marked } from 'marked';

export default function PDFExportButton({ report, template }: { report: LiverReport, template: any }) {
    const [isExporting, setIsExporting] = useState(false);

    const handleExport = async () => {
        setIsExporting(true);
        try {
            // Because html2canvas inherently crashes when attempting to parse Tailwind v4's globally-injected root oklch/lab variables 
            // from the document stylesheets (even when isolated in iframes or passed as strings), the most robust and elegant 
            // solution for Next.js 15 App Router is utilizing a clean, sandboxed native print window.
            const newWindow = window.open('', '_blank');
            if (!newWindow) {
                toast.error("Please allow popups to generate PDF");
                return;
            }

            const brandingColor = template?.primary_color || '#1E3A8A';
            const hospitalName = template?.hospital_name || 'HepatoScope Clinic';
            const disclaimer = template?.disclaimer_text || 'This report is generated by an AI assistant based on inputted lab values. It is not a substitute for professional medical advice.';

            const aiSummaryHtml = report.ai_summary ? await marked.parse(report.ai_summary) : 'No AI summary was generated for this report.';

            const htmlString = `
                <div style="font-family: Arial, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; background-color: #ffffff;">
                    
                    <!-- Header -->
                    <div style="border-bottom: 3px solid ${brandingColor}; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end;">
                        <div>
                            ${template?.logo_url ? `<img src="${template.logo_url}" alt="Logo" style="max-height: 60px; margin-bottom: 10px;" />` : ''}
                            <h1 style="color: ${brandingColor}; margin: 0; font-size: 28px;">${hospitalName}</h1>
                            <p style="margin: 5px 0 0 0; font-size: 14px; color: #666;">Liver Function Analysis Report</p>
                        </div>
                        <div style="text-align: right; font-size: 12px; color: #555;">
                            <p style="margin: 0;">Date: ${new Date(report.created_at).toLocaleDateString()}</p>
                            <p style="margin: 5px 0 0 0;">Report ID: ${report.id.substring(0, 8)}...</p>
                        </div>
                    </div>

                    <!-- Patient Info -->
                    <div style="background-color: #f9fafb; padding: 15px 20px; border-radius: 8px; margin-bottom: 30px;">
                        <table style="width: 100%; border-collapse: collapse;">
                            <tr>
                                <td style="padding: 5px 0; width: 50%;"><strong>Patient Name:</strong> ${report.patient_name}</td>
                                <td style="padding: 5px 0; width: 50%;"><strong>Risk Level:</strong> <span style="color: ${report.risk_level === 'High' ? '#DC2626' : report.risk_level === 'Moderate' ? '#D97706' : '#059669'}; font-weight: bold;">${report.risk_level.toUpperCase()} (Score: ${report.risk_score})</span></td>
                            </tr>
                            <tr>
                                <td style="padding: 5px 0;"><strong>Age:</strong> ${report.age} years</td>
                                <td style="padding: 5px 0;"><strong>Gender:</strong> ${report.gender}</td>
                            </tr>
                        </table>
                    </div>

                    <!-- Lab Results -->
                    <h3 style="color: ${brandingColor}; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">Laboratory Results</h3>
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 40px;">
                        <thead>
                            <tr style="background-color: #f3f4f6; text-align: left;">
                                <th style="padding: 12px; border: 1px solid #e5e7eb;">Test</th>
                                <th style="padding: 12px; border: 1px solid #e5e7eb;">Result</th>
                                <th style="padding: 12px; border: 1px solid #e5e7eb;">Reference Range</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">Total Bilirubin</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.total_bilirubin} mg/dL</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">0.1 - 1.2 mg/dL</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">Albumin</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.albumin} g/dL</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">3.4 - 5.4 g/dL</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">SGPT (ALT)</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.sgpt} U/L</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">7 - 56 U/L</td>
                            </tr>
                            <tr>
                                <td style="padding: 12px; border: 1px solid #e5e7eb;">SGOT (AST)</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; font-weight: bold;">${report.sgot} U/L</td>
                                <td style="padding: 12px; border: 1px solid #e5e7eb; color: #666;">8 - 48 U/L</td>
                            </tr>
                        </tbody>
                    </table>

                    <!-- AI Synthesis -->
                    <h3 style="color: ${brandingColor}; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 20px;">AI Medical Synthesis</h3>
                    <div style="background-color: #f8fafc; padding: 20px; border-left: 4px solid ${brandingColor}; line-height: 1.6; font-size: 14px; margin-bottom: 50px;">
                        ${aiSummaryHtml}
                    </div>

                    <!-- Footer -->
                    <div style="margin-top: auto; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; font-size: 10px; color: #888;">
                        <p>${disclaimer}</p>
                    </div>
                </div>
            `;

            // Setup native print options
            newWindow.document.write(`
                <html>
                    <head>
                        <title>Liver_Report_${report.patient_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}</title>
                        <style>
                            @media print {
                                @page { margin: 10mm; }
                                body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                            }
                        </style>
                    </head>
                    <body onload="setTimeout(() => { window.print(); window.close(); }, 250);">
                        ${htmlString}
                    </body>
                </html>
            `);
            newWindow.document.close();

            toast.success("PDF Exported Successfully");

        } catch (error) {
            console.error(error);
            toast.error("Failed to generate PDF");
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="flex items-center gap-3 no-print">
            <button
                onClick={handleExport}
                disabled={isExporting}
                className="flex items-center gap-2 px-5 py-2.5 bg-[#1E3A8A] hover:bg-[#152b66] text-white rounded-lg font-bold text-sm transition-colors shadow-sm disabled:opacity-70 disabled:cursor-not-allowed"
            >
                {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                {isExporting ? 'Generating...' : 'Export PDF'}
            </button>
        </div>
    );
}
